# Generated by Django 2.2.4 on 2019-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
