# Generated by Django 2.2.4 on 2019-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0002_auto_20190920_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='uid',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
    ]
