# Generated by Django 2.2.4 on 2019-09-27 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0005_auto_20190927_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='p_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
