# Generated by Django 2.2.4 on 2019-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence_tracker', '0006_auto_20190927_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='p_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
